#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "gruvbox"
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    default_indent = 4
    relativenumber = false
    spacevim_project_rooter_automatically = false
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'unite'

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "format"

[[custom_plugins]]
  name = "brookhong/cscope.vim"
  merged = false

[[custom_plugins]]
#name = 'flrnprz/plastic.vim'
#name = 'wmvanvliet/vim-blackboard'
#name = 'chase/focuspoint-vim'
#name = 'sonjapeterson/1989.vim'
#name = 'gosukiwi/vim-atom-dark'
    name = 'joshdick/onedark.vim'
      # note: you need to disable merged feature
    merged = false

[[custom_plugins]]
    name = "ap/vim-css-color"
    merged = false

[[custom_plugins]]
    name = "vim-scripts/DoxygenToolkit.vim"
    merged = false
